query projects {
  projects(first: 6, orderBy: date_DESC) {
    id
    name
    description
    slug
    tags
    sourceCode
    image {
      id
      handle
    }
  }
  projectsIntro(where: { slug: "selected-projects" }) {
    title
    intro
  }
}
